openapi: 3.1.0
info:
  title: Parameters and responses manipulation
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'
paths:
  /users:
    get:
      parameters:
        - name: page
          in: query
          schema:
            type: int
          required: true
        - name: size
          in: query
          schema:
            type: int
          required: true
      responses:
        200:
          description: List of users found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: int
                    name:
                      type: string
                    email:
                      type: string
                  example:
                    id: 1,
                    name: Alice,
                    email: alice@example.com
        400:
          description: Bad types for provided query parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                example:
                  error: Bad types for provided query parameters
  
