openapi: 3.1.0
info:
  title: Use components/parameters to centralize parameter definitions
  description: Use components/parameters to centralize parameter definitions
  version: 1.0.0
servers:
  - url: 'http:localhost:8000'

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
  parameters:
    Limit:
      name: limit
      in: query
      schema:
        type: integer
        minimum: 1
      required: false
      description: Maximum number of products to be returned
    Query:
      name: q
      in: query
      schema:
        type: string
      required: false
      description: Search term
paths:
  /products:
    get:
      parameters:
        - $ref: "#/components/parameters/Limit"
        - $ref: "#/components/parameters/Query"
      responses:
        200:
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
  
