openapi: 3.1.0
info:
  title: API with authentication + tags
  description: API with authentication + tags
  version: 1.0.0
servers:
  - url: 'http:localhost:8000'

tags:
  - name: Products
    description: Product management related-activities

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
    Order:
      type: object
      properties:
        identifier:
          type: integer
        customer_name:
          type: string
        creation_datetime:
          type: string
          format: date-time
        total_amount:
          type: number
          format: float
  parameters:
    Limit:
      name: limit
      in: query
      schema:
        type: integer
        minimum: 1
        required: false
        description: Maximum number of products to be returned
    Query:
      name: q
      in: query
      schema:
        type: string
        required: false
        description: Search term

paths:
  /products:
    get:
      tags:
        - Products
      parameters:
        - $ref: "#/components/parameters/Limit"
        - $ref: "#/components/parameters/Query"
      responses:
        200:
          description: List of Products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
              examples:
                nonEmptyList:
                  summary: List of products
                  value:
                    - name: "Milk"
                      expiration_datetime: "2026-08-31T17:45:30Z"
                      price: 12000.0
                    - name: "Cookies"
                      expiration_datetime: "2025-12-22T10:25:37Z"
                      price: 25000.0
                emptyList:
                  summary: Empty List
                  value: []

  
